import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import MainPage from "@/page/MainPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mero share",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainPage>
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
          {children}
        </MainPage>
        </body>
    </html>
  );
}
